import email
from sqlalchemy.orm.session import Session
from db.hash import Hash
from schemas import UserBase
from db.models import DbUser

def create_user(request: UserBase, db: Session):
    new_user = DbUser(
        username = request.username,
        email = request.email,
        password = Hash.bcrypt(request.password)
    )

    db.add(new_user)
    db.commit()
    db.refresh(new_user) # we need to refresh so once the database creates the new user, we need the id that was auto generated by the db.
    return new_user


def get_all_users(db: Session): 
    return db.query(DbUser).all()


def find_user_by_id(id: int, db: Session):
    return db.query(DbUser).filter(DbUser.id == id).first()